# Generated by Django 5.0.4 on 2024-04-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_student_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_log',
        ),
    ]
